title: Bhuvisha Udayakumar
description: Law Student | Legal Research | IPR | Civil & Criminal Law
theme: minima
author: Bhuvisha Udayakumar
email: ukbhuviudaya@gmail.com
linkedin_username: bhuvisha
show_excerpts: false
